// Interface Declaration: InfoSpecific ( comp )

type OPENINFO_CLOSED = "CLOSED";
type OPENINFO_LOCATION = "LOCATION";
type OPENINFO_MENU = "MENU";
type OPENINFO_WORKTIME = "WORKTIME";
type OPENINFO_CONTACT = "CONTACT";
type OPENINFO_IMAGE = "IMAGE";
type OPENINFO_REVIEW = "REVIEW";
type OPENINFO_EVENT = "EVENT";

type OPENINFO_ADD_LOCATION = "ADD/LOCATION";
type OPENINFO_ADD_MENU = "ADD/MENU";
type OPENINFO_ADD_WORKTIME = "ADD/WORKTIME";
type OPENINFO_ADD_CONTACT = "ADD/CONTACT";
type OPENINFO_ADD_IMAGE = "ADD/IMAGE";
type OPENINFO_ADD_REVIEW = "ADD/REVIEW";
type OPENINFO_ADD_EVENT = "ADD/EVENT";

export type InfoSpecificOpenInfoType =
    OPENINFO_CLOSED | OPENINFO_LOCATION | OPENINFO_MENU | OPENINFO_WORKTIME | OPENINFO_CONTACT | OPENINFO_IMAGE | OPENINFO_REVIEW | OPENINFO_EVENT |
    OPENINFO_ADD_LOCATION | OPENINFO_ADD_MENU | OPENINFO_ADD_WORKTIME | OPENINFO_ADD_CONTACT | OPENINFO_ADD_IMAGE | OPENINFO_ADD_REVIEW | OPENINFO_ADD_EVENT ;


type OPENSIZE_CLOSED = "CLOSED";
type OPENSIZE_MEDIUM = "MEDIUM";
type OPENSIZE_LARGE = "LARGE";

export type InfoSpecificOpenSize = OPENSIZE_CLOSED | OPENSIZE_MEDIUM | OPENSIZE_LARGE;