// Interface Declaration: InfoSpecific ( comp )

type OPENINFO_CLOSED = "CLOSED";
type OPENINFO_LOCATION = "LOCATION";
type OPENINFO_MENU = "MENU";
type OPENINFO_WORKTIME = "WORKTIME";
type OPENINFO_CONTACT = "CONTACT";
type OPENINFO_IMAGE = "IMAGE";
type OPENINFO_REVIEW = "REVIEW";
type OPENINFO_EVENT = "EVENT";

export type InfoSpecificOpenInfoType = OPENINFO_CLOSED | OPENINFO_LOCATION | OPENINFO_MENU | OPENINFO_WORKTIME | OPENINFO_CONTACT | OPENINFO_IMAGE | OPENINFO_REVIEW | OPENINFO_EVENT;


type OPENSIZE_CLOSED = "CLOSED";
type OPENSIZE_MEDIUM = "MEDIUM";
type OPENSIZE_LARGE = "LARGE";

export type InfoSpecificOpenSize = OPENSIZE_CLOSED | OPENSIZE_MEDIUM | OPENSIZE_LARGE;