# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm install
    
    - run: mkdir -p ./src/keys && echo '{}' > ./src/keys/api.json
    
    - run: echo 'REACT_APP_DB_HOST=${{ secrets.REACT_APP_DB_HOST }}\nREACT_APP_BACKEND_HOST=${{ secrets.REACT_APP_BACKEND_HOST }}\nHTTPS=true\nSSL_CRT_FILE=${{ secrets.SSL_CRT_FILE }}\nSSL_KEY_FILE=${{ secrets.SSL_KEY_FILE }}' > ./.env.production
    
    - run: pwd
    
    - run: ls -al
    
    - run: cat ./src/keys/api.json
    
    - run: npm run build
      env:
        CI: false
      
    
    # execute pull command to service server
          
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.UNAME }}
        password: ${{ secrets.PASSWD }}
        port: ${{ secrets.PORT }}
        source: '/home/runner/work/AJ_MealMap/AJ_MealMap/*'
        target: '/project/mealmap'

    - name: execute remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.UNAME }}
        password: ${{ secrets.PASSWD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf /project/mealmap/AJ_MealMap/*
          mv -R /project/mealmap/github/workspace /project/mealmap/AJ_MealMap
          rm -rf /project/mealmap/github
