# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSH_Automizer

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v2
        
    - name: execute remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.UNAME }}
        password: ${{ secrets.PASSWD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf /project/mealmap/tmp
          git clone -b publish --single-branch https://github.com/nate-crema/AJ_MealMap /project/mealmap/tmp
          rm -rf /project/mealmap/AJ_MealMap/*
          cp -R /project/mealmap/tmp/* /project/mealmap/AJ_MealMap
          cd /project/mealmap/AJ_MealMap && yarn
          yarn build
